version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - whosaid-db-data:/var/lib/postgresql/data/

networks:
  postgres-network:
    driver: bridge

volumes:
  whosaid-db-data: